apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.bluemix.net/mutual-auth: secretName=client-tls-a6bc9016c033abe5dfd018aaa3a38e6f
      port=443 serviceName=apic-analytics-analytics-client
    ingress.bluemix.net/redirect-to-https: "True"
    ingress.bluemix.net/ssl-services: ssl-service=apic-analytics-analytics-client
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    productID: e972cbf3064c4d6a908e095f9622dd2b
    productName: Analytics
    productVersion: 2018.4.1.7-ifix1.5
  creationTimestamp: "2020-06-06T03:01:47Z"
  generation: 3
  labels:
    app: apic-analytics-analytics-client
    chart: apic-analytics-2.0.0
    heritage: Tiller
    release: apic-analytics
  name: apic-analytics-analytics-client
  namespace: default
  resourceVersion: "792541"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/apic-analytics-analytics-client
  uid: 0fb8bbda-a7a2-11ea-80dc-005056a378ae
spec:
  rules:
  - host: sub.domain.com.vn
    http:
      paths:
      - backend:
          serviceName: test-domain-com-vn
          servicePort: 443
        path: /
  tls:
  - hosts:
    - sub.domain.com.vn
status:
  loadBalancer:
    ingress:
    - {}
